name: Django CI/CD - Staging

on:
  push:
    branches:
      - staging

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Migrations
      run: |
        python backend/manage.py migrate

    - name: Run Django Checks
      run: |
        python backend/manage.py check --deploy

    - name: Deploy to Staging Environment
      env:
        STAGING_SECRET_KEY: ${{ secrets.STAGING_SECRET_KEY }}
      run: |
        echo "Deploying to staging..."
        # Masukkan script deployment staging Anda di sini
